### PR TITLE
change image_raw to async

### PR DESCRIPTION
**Pull request by ratsclub**
This improved the image loading quite a bit on my cheap VPS :sweat_smile:

### CODE REVIEW

**Comment by sirodoht** [comment]
@ratsclub interesting! How do you measure it? I would imagine it makes no different since it's the only operation in the view.

Also, does this require an ASGI server (eg. uvicorn) rather than gunicorn, which is what we currently use?

**Comment by ratsclub** [comment]
> interesting! How do you measure it?

I'm hosting my instance on Hetzner with about 250ms of latency. I tested this with a post containing dozens of images. The results I had was that the sync request tried to load the images in order while the async loaded the smaller images first.

> Also, does this require an ASGI server (eg. uvicorn) rather than gunicorn

You can continue using `gunicorn` just fine, but should run `uvicorn` to have the proper async support which is what I'm running on my server. See [Asynchronous support](https://docs.djangoproject.com/en/5.0/topics/async/#asynchronous-support) on the docs.

By the way, another thing that could be improved on the html generation is to make all `img` tags have `loading=lazy` by default.

**Comment by thiagokokada** [comment]
> @ratsclub interesting! How do you measure it? I would imagine it makes no different since it's the only operation in the view.
> 
> Also, does this require an ASGI server (eg. uvicorn) rather than gunicorn, which is what we currently use?

I can try to answer some questions since I helped @ratsclub with this issue.

@ratsclub said that the issue happens especially in posts with multiple high resolution images in high latency connections (250ms+), when just some images would load at a time.

I imagine the reason is that since each blog post is loaded in a synchronous way, they're going to block the thread until the image is loaded on the other client. Async can help since once the request for the image is waiting for I/O (and this can take a while for bigger images), the thread can be released and and start handle another request.

It seems @ratsclub is using uvicorn, and I am not sure what the impact is on gunicorn, but from looking at the documentation it seems it shouldn't make a difference, it is just that gunicorn wouldn't have the advantages that uvicorn can have.

**Comment by sirodoht** [comment]
Thanks @ratsclub and @thiagokokada! That sounds great! I'll test this and merge it :D

**Pull request merged**
