### PR TITLE
Add sitemap.xml support

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a new path, /sitemap.xml. This file is used to improve search engine optimization and should reduce server load, as search machines are not required to re-scan every page looking for changes.

It works through a new view, which in turn creates a PostSitemap and PageSitemap object based on the requested username. This process happens through the Django Sitemap plugin.

### CODE REVIEW

**Comment by sirodoht** [comment]
Oh wow! Amazing, thank you! I'm merging this, but just one question. How did you conclude on `1.0` and `0.8` priorities?

Also, maybe it'd be nice to have one test case, that this thing doesn't break, as well as that the hidden pages remain hidden. If you're up for it, freel free to add them, if not no worries at all.

**Comment by ghost** [comment]
The priorities are kind of random. As far as I and many SEO resources are concerned, the priorities do not achieve anything in any modern search engines. There even is a tweet from a Google engineer saying that the Googlebot ignores those: https://twitter.com/methode/status/846796737750712320

I still added theme because they still are somehow recommended, and posts have a higher priority than pages because it feels like when you research something you are far more likely looking for a blog post than a blog page.

Regarding the test cases, I will add those tomorrow. I did not add them initially, as most of my code is just copy-pasted from the existing RSS/syndicaiton implementations which did not feature tests themselves.

**Comment by sirodoht** [comment]
> As far as I and many SEO resources are concerned, the priorities do not achieve anything in any modern search engines.

OK, cool.

> Regarding the test cases, I will add those tomorrow. 

Let me know if you need any help. Feel free to email me or chat on Telegram.

**Comment by ghost** [comment]
So, I added unit tests for the sitemap.xml itself, and also for the RSS feed since they are very similar. While doing this I noticed that my test failed because the blog description/byline field was rendered incorrectly, which I fixed.

Furthermore I added the index page of a blog to the sitemap.

For the future we should add some tests around custom domain routing, as they don't have any tests yet AFAIK.

**Review by sirodoht — APPROVED** [review]
Thanks! That's awesome. I'll merge it tomorrow :)

**Pull request merged**
